[build]
publish = "public"
command = "npx tinacms build && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.146.1"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# TODO: doesn't work
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.146.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.146.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


